name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for putting the first issue on our Github! We will look into it soon!'
        pr-message: 'Thanks for putting the Pull Request (PR) on our Github! We will look into it soon!'
